version: 0.0.{build}

configuration:
  - Release

before_build:
  - nuget restore
  
build:
  verbosity: minimal

deploy:
  release: myproduct-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: UwlUsxmCnB4x74TJI5h/rhwxxw9YVcj0rjspm6YteHgQyDf5BDTVxNRSn6Z2QLAD
  artifact: libDatabaseHelper\bin\Release\libDatabaseHelper.dll
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: false
