version: 0.0.{build}

configuration:
  - Release

before_build:
  - nuget restore
  
build:
  verbosity: minimal

deploy:
  release: myproduct-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: 35311f98390f8fc7694a55a0c5a5a662a895bd8e
  artifact: libdatabasehelper\libDatabaseHelper\bin\Release\libDatabaseHelper.dll
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: false
