version: 0.0.{build}

configuration:
  - Release

before_build:
  - nuget restore
 
build:
  verbosity: minimal

after_build:
  - del /s deploy\*.pdb
  - 7z a builds_v%APPVEYOR_BUILD_VERSION%.zip deploy\*
  - appveyor PushArtifact builds_v%APPVEYOR_BUILD_VERSION%.zip

deploy:
  release: libDatabaseHelper-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: UwlUsxmCnB4x74TJI5h/rhwxxw9YVcj0rjspm6YteHgQyDf5BDTVxNRSn6Z2QLAD
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: false
