version: 1.0.{build}
matrix:
  allow_failures:
    - configuration: 2008
      platform: x64
      
configuration:
  - 2008
  
platform:
  - x86
  - x64
  
before_build:
  - nuget restore
  
build:
  verbosity: minimal
