using System;
using System.Linq;

using libDatabaseHelper.classes.generic;

namespace libDatabaseHelper.classes.sqlce.entities
{
    [TableProperties(Registration = TableProperties.RegistrationType.RegisterOnDatabaseManager)]
    public class AuditEntry : DatabaseEntity
    {
        [TableColumn(IsPrimaryKey = true, IsAutogenerated = true)]
        public long AuditId;

        [TableColumn()] 
        public DateTime TimeOfOccurence;

        [TableColumn()]
        public string Message;

        public static AuditEntry AddAuditEntry(DatabaseEntity entity, string message)
        {
            var entry = new AuditEntry
            {
                Message = message + " : " + entity.ToContentString(),
                TimeOfOccurence = DateTime.Now
            };
            try
            {
                entry.Add();
            }
            catch (Exception ex) { Console.WriteLine(ex.Message); }
            return entry;
        }
    }
}
