using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Data;

using libDatabaseHelper.classes.generic;
using System.Data.Common;
using System.Data.SqlServerCe;

namespace libDatabaseHelper.classes.sqlce
{
    public class DatabaseEntity : GenericDatabaseEntity
    {
        private bool _fillFromUniques = true;

        public DatabaseEntity()
        {
        }

        protected override DatabaseType FetchDatbaseType()
        {
            return DatabaseType.SqlCE;
        }

        protected override bool OnAdd(TransactionObject transaction)
        {
            var paramString         = "";
            var valueString         = "";
            var result              = GetColumns(true);
            var command             = transaction.GetCommand();
            FieldInfo autogenField  = null;

            foreach (var field in result.GetOtherColumns().Where(i => ! ((TableColumn)i.GetCustomAttributes(typeof(TableColumn), true)[0]).IsAutogenerated))
            {
                valueString += (valueString == "" ? "" : ", ") + field.Name;
                paramString += (paramString == "" ? "@" : ", @") + field.Name;
                var val = field.GetValue(this);
                val = val is ICustomType ? (val as ICustomType).GetValue() : val;
                GenericUtils.AddWithValue(ref command, "@" + field.Name, val);
            }

            foreach (var field in from field in result.GetOtherColumns().Where(i => ((TableColumn)i.GetCustomAttributes(typeof(TableColumn), true)[0]).IsAutogenerated) let col = ((TableColumn)field.GetCustomAttributes(typeof(TableColumn), true)[0]) where col != null && col.IsAutogenerated && GenericFieldTools.IsTypeNumber(field.FieldType) select field)
            {
                autogenField = field;
            }

            try
            {
                var commandString = "INSERT INTO " + GetType().Name + "( " + valueString + " ) VALUES ( " + paramString + " )";
                command.CommandText = commandString;

                if (command.ExecuteNonQuery() <= 0)
                {
                    return false;
                }

                transaction.Commit();
            }
            catch (System.Exception)
            {
                transaction.Rollback();
                return false;
            }

            if (autogenField != null)
            {
                command.CommandText = "SELECT @@IDENTITY";
                var valReturned = command.ExecuteScalar();

                autogenField.SetValue(this, GenericFieldTools.ConvertToType(autogenField.FieldType, valReturned));
            }

            return true;
        }

        protected override bool OnUpdate(TransactionObject transaction)
        {
            var valueParamString        = "";
            var primaryValueParamString = "";
            var result                  = GetColumns(true);
            var command                 = transaction.GetCommand();

            foreach (var field in result.GetOtherColumns())
            {
                if (result.GetPrimaryKeys().Contains(field))
                    continue;

                valueParamString += (valueParamString == "" ? "" : ", ") + (field.Name + " = @" + field.Name);

                var val = field.GetValue(this);
                val = val is ICustomType ? (val as ICustomType).GetValue() : val;

                GenericUtils.AddWithValue(ref command, "@" + field.Name, val);
            }

            foreach (var field in result.GetPrimaryKeys())
            {
                primaryValueParamString += (primaryValueParamString == "" ? "" : " AND ") + (field.Name + " = @" + field.Name);

                var val = field.GetValue(this);
                val = val is ICustomType ? (val as ICustomType).GetValue() : val;

                if (command.Parameters.Contains("@" + field.Name))
                    command.Parameters["@" + field.Name].Value = val;
                else
                    GenericUtils.AddWithValue(ref command, "@" + field.Name, val);
            }

            var commandString = "UPDATE " + GetType().Name + " SET " + valueParamString + " WHERE " + primaryValueParamString;
            
            try
            {
                command.CommandText = commandString;
                var executionResult = command.ExecuteNonQuery();

                transaction.Commit();

                return (executionResult > 0);
            }
            catch (System.Exception)
            {
                transaction.Rollback();
            }
            return false;
        }

        protected override bool OnRemove(TransactionObject transaction)
        {
            var primaryValueParamString = "";
            var result                  = GetColumns();
            var command                 = transaction.GetCommand();

            foreach (var field in result.GetPrimaryKeys())
            {
                primaryValueParamString += (primaryValueParamString == "" ? "" : " AND ") +
                                           (field.Name + " = @" + field.Name);

                var val = field.GetValue(this);
                val = val is ICustomType ? (val as ICustomType).GetValue() : val;

                GenericUtils.AddWithValue(ref command, "@" + field.Name, val);
            }

            var commandString = "DELETE FROM " + GetType().Name + " WHERE " + primaryValueParamString;

            try
            {
                command.CommandText = commandString;
                var executionResult = command.ExecuteNonQuery();

                transaction.Commit();

                return (executionResult > 0);
            }
            catch (System.Exception)
            {
                transaction.Rollback();
            }
            return false;
        }

        public override GenericDatabaseEntity.ExistCondition Exist(bool onlyCheck, TransactionObject transaction = null)
        {
            var result = GetColumns(true);
            if (result == null || result.GetPrimaryKeys() == null || !result.GetPrimaryKeys().Any())
            {
                throw new DatabaseException(DatabaseException.ErrorType.NoPrimaryKeyColumnsFound);
            }

            if (transaction == null)
            { 
                var connection = GenericConnectionManager.GetConnectionManager(_supportedDatabase).GetConnection(_entityType);
                transaction = TransactionObject.CreateTransactionObject(_supportedDatabase, connection);
            }

            var command                         = transaction.GetCommand();
            var primaryValueParamString         = "";
            var inversePrimaryValueString       = "";
            var filteredFields                 = (onlyCheck ? result.GetPrimaryKeys() : result.GetPrimaryKeys().Where(i => !((TableColumn)i.GetCustomAttributes(typeof(TableColumn), true)[0]).IsAutogenerated)).ToArray();

            foreach (var field in filteredFields)
            {
                primaryValueParamString += (primaryValueParamString == "" ? "" : " AND ") +
                                           (field.Name + " = @" + field.Name);
                inversePrimaryValueString += (inversePrimaryValueString == "" ? "" : " AND ") +
                                             (field.Name + " != @" + field.Name);

                var val = field.GetValue(this);
                val = val is ICustomType ? (val as ICustomType).GetValue() : val;

                GenericUtils.AddWithValue(ref command, "@" + field.Name, val);
            }

            var commandString = "SELECT * FROM " + GetType().Name + " WHERE " + primaryValueParamString;
            command.CommandText = commandString;

            var cell = filteredFields.Any() ? command.ExecuteScalar() : null;

            var uniqueValueParamString = "";

            foreach (var field in result.GetOtherColumns().Where(i => ((TableColumn) i.GetCustomAttributes(typeof (TableColumn), true)[0]).IsUnique))
            {
                uniqueValueParamString += (uniqueValueParamString == "" ? "" : " OR ") + (field.Name + " = @" + field.Name);

                var val = field.GetValue(this);
                val = val is ICustomType ? (val as ICustomType).GetValue() : val;

                GenericUtils.AddWithValue(ref command, "@" + field.Name, val);
            }

            if (uniqueValueParamString == "")
            {
                return cell == null ? ExistCondition.None : ExistCondition.RecordExists;
            }

            commandString       = "SELECT * FROM " + GetType().Name + " WHERE " + (cell != null ? ("( " + inversePrimaryValueString + ") AND (") : "(") + uniqueValueParamString + ")";
            command.CommandText = commandString;
            var reader          = command.ExecuteReader();
            var hadData         = false;

            if (reader != null)
            {
                if (_fillFromUniques && reader.Read())
                {
                    foreach (var field in result.GetPrimaryKeys())
                    {
                        field.SetValue(this, GenericFieldTools.ConvertToType(field.FieldType, reader[field.Name]));
                    }
                    hadData = true;
                }
                reader.Close();
            }

            if (cell == null && hadData == false)
                return ExistCondition.None;

            return (cell != null ? ExistCondition.RecordExists : 0) | (hadData ? ExistCondition.UniqueKeyExists : 0);
        }

        public static string GetSelectCommandString<T>()
        {
            return GetSelectCommandString(typeof(T));
        }

        public static string GetSelectCommandString(Type type)
        {
            if (selectCommandStrings.ContainsKey(type))
                return selectCommandStrings[type];

            var cInstanceName = type.Name + "_1";

            var obj = GenericDatabaseEntity.GetNonDisposableRefenceObject(type);

            if (obj == null) return "";

            var fields = obj.GetColumns(true).GetOtherColumns().Where(i => ((TableColumn)i.GetCustomAttributes(typeof(TableColumn), true)[0]).IsRetrievableFromDatabase);

            var selectList = "";
            var dict = new Dictionary<Type, int>();

            foreach (var fieldInfo in fields)
            {
                var attr = (TableColumn)fieldInfo.GetCustomAttributes(typeof(TableColumn), true)[0];
                selectList += (selectList == "" ? "" : ", ");
                if (attr.ReferencedField != null && attr.ReferencedClass != null)
                {
                    var i = 0;
                    if (!dict.ContainsKey(attr.ReferencedClass))
                    {
                        dict.Add(attr.ReferencedClass, ++i);
                    }
                    else
                    {
                        i = dict[attr.ReferencedClass];
                        dict[attr.ReferencedClass] = ++i;
                    }

                    var cobj = (Activator.CreateInstance(attr.ReferencedClass) as IComboBoxItem);
                    if (cobj == null)
                    {
                        throw new DatabaseEntityException("Invalid referee class specified. The type specified : " + attr.ReferencedClass.Name + ", should be of type IComboBoxItem");
                    }

                    selectList += "(CASE WHEN " + cInstanceName + "." + fieldInfo.Name + " IN ( SELECT " + attr.ReferencedField + " FROM " +
                                  attr.ReferencedClass.Name + " ) THEN (SELECT " +
                                  cobj.GetSelectQueryItems().Replace("[OBJ]", attr.ReferencedClass.Name) + " FROM " +
                                  attr.ReferencedClass.Name + " WHERE " + cInstanceName + "." + fieldInfo.Name + " = " + attr.ReferencedClass.Name + "." +
                                  attr.ReferencedField + " LIMIT 1) ELSE \"\" END) as [" + attr.GridDisplayName + "]";
                }
                else
                {
                    selectList += cInstanceName + "." + fieldInfo.Name + " as [" + ((attr.GridDisplayName == null || attr.GridDisplayName.Trim() == "") ? fieldInfo.Name : attr.GridDisplayName) + "]";
                }
            }

            var selectCommand = "SELECT " + selectList + " FROM " + type.Name + " " + cInstanceName /*+ innerJoinQuery*/;

            selectCommandStrings.Add(type, selectCommand);

            return selectCommand;
        }
    }
}